cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:painting_id>/', views.cart_add, name='cart_add'),
    path('', views.items_in_cart, name='items_in_cart'),
]

fergusonart/urls.py
from django.contrib import admin
from django.urls import include, path 
from gallery import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('gallery/', include('gallery.urls')),
    path('search/', include('search_application.urls')),
    path('cart/', include('cart.urls')),
    path('place_orders/', include('place_orders.urls')),
    path('user_accounts/user_signup/', views.signupTemp, name='signup'),
    path('user_accounts/user_signin/', views.signinTemp, name='login'),
    path('user_accounts/user_signout/', views.signoutTemp, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views

app_name='gallery'

urlpatterns = [
    path('', views.shopByStyle, name='shopByStyle'),
    path('<slug:s_slug>/', views.shopByStyle, name='paintings_by_style'),
    path('<slug:s_slug>/<slug:painting_slug>/', views.paintStyleDetail, name='paintStyleDetail'),
]

cart/models.py
from django.db import models
from gallery.models import Painting

class Cart(models.Model):
    new_cart_id = models.CharField(max_length=75, blank=True)
    date_added= models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.new_cart_id

class CartAddItem(models.Model):
    painting = models.ForeignKey(Painting, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartAddItem'

    def sub_total(self):
        return self.painting.price * self.quantity

    def __str__(self):
        return self.painting

cart/views.py
import stripe
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_list_or_404
from .models import Cart, CartAddItem
from gallery.models import Painting
from place_orders.models import placeOrder, yourItem


# session id created view #
def new_cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# items added to new cart view#
def cart_add(request, painting_id):
    painting = Painting.objects.get(id=painting_id)
    try:
        cart = Cart.objects.get(new_cart_id=new_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            new_cart_id = new_cart_id(request))
        cart.save()
    try:
        add_cart_item = CartAddItem.objects.get(painting=painting, cart=cart)
        if add_cart_item.quantity < add_cart_item.painting.quantity:
            add_cart_item.quantity += 1
            add_cart_item.save()
    except CartAddItem.DoesNotExist:
        add_cart_item = CartAddItem.objects.create(painting = painting, quantity = 1, cart = cart)
        add_cart_item.save()
    return redirect('cart:items_in_cart')

# funct that checks new items in cart view #
def items_in_cart(request, total=0, counter=0, add_cart_items = None):
    try:
        cart = Cart.objects.get(new_cart_id=new_cart_id(request))
        add_cart_items = CartAddItem.objects.filter(cart=cart, active=True)
        for add_cart_item in add_cart_items:
            total += (add_cart_item.painting.price * add_cart_item.quantity)
            counter += add_cart_item.quantity
    except ObjectDoesNotExist: 
        pass

#stripe data
    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_cc_total = int(total * 100)
    description = 'Ferguson Virtual Gallery'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billingName = request.POST['stripeBillingName']
            customer = stripe.Customer.create(
                email=email
            )
            charge = stripe.Charge.create(
                customer=customer.id,
                amount=stripe_cc_total,
                currency='usd',
                description=description
            )
            try:
                items_in_order = placeOrder.objects.create(
                    token = token,
                    billingName = billingName, 
                    emailAddress = email, 
                    total= total
                )
                items_in_order.save()
                for order_item_added in add_cart_items:
                    yi = YourItem.objects.create(
                        painting = order_item_added.painting.title,
                        price = order_item_added.painting.price,
                        quantity = order_item_added.quantity,
                        order = items_in_order
                        )
                    yi.save()

                    paintings = Painting.objects.get(id=order_item_added.painting.id)
                    paintings.quantity = int(order_item_added.painting.quantity - order_item_added.quantity)
                    paintings.save()
                    order_item_added.delete()

                return redirect('place_orders:confirmation', order_item_added.id)
            except ObjectDoesNotExist: 
                pass
        except stripe.error.CardError as e: 
            return False,e
    return render(request, 'cart.html', dict(add_cart_items = add_cart_items, total = total, stripe_cc_total = stripe_cc_total, counter = counter, data_key = data_key, description = description))

cart/templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
    {% if not add_cart_items %}
        <div>
            <div class="text-center">
                <p class="text-center page_title">
                    Your cart is empty. Click <a href="{% url 'gallery:shopByStyle' %}">here</a> to return to the gallery.
                </p>
            </div>
        </div>
    {% else %}    
        <div>
            <div class="text-center">
                <h1 class="text-center page_title">
                    <br>
                    Your Shopping Cart
                </h1>
            </div>
        </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table checkout-table">
                <thead class="checkout-table-head">
                    <tr>
                        <th>
                            Your Order: Your total is ${{ total }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for add_cart_item in add_cart_items %}
                        <tr>
                            <td>
                                <strong>Title: {{add_cart_item.painting.title}}</strong>
                                <br>
                                Id: {{add_cart_item.painting.id}}
                                <br>
                                Qty: {{add_cart_item.quantity}} | Price: ${{add_cart_item.painting.price}}
                                <br>
                                Sub Total: ${{add_cart_item.sub_total}}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table checkout-table">
                    <thead class="checkout-table-head">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Review your order and proceed to checkout. 
                        </td>
                    </tr>
                </tbody>
            </table>
            

            <div id="paypal-button"></div>
            <script src="https://www.paypalobjects.com/api/checkout.js"></script>
            <script>
              paypal.Button.render({
                // Configure environment
                env: 'sandbox',
                client: {
                  sandbox: 'demo_sandbox_client_id',
                  production: 'demo_production_client_id'
                },

                locale: 'en_US',
                style: {
                  size: 'small',
                  color: 'gold',
                  shape: 'pill',
                },
            
                commit: true,
            
                payment: function(data, actions) {
                  return actions.payment.create({
                    transactions: [{
                      amount: {
                        total: '0.01',
                        currency: 'USD'
                      }
                    }]
                  });
                },

                onAuthorize: function(data, actions) {
                  return actions.payment.execute().then(function() {
                    window.alert('Thank you for your purchase!');
                  });
                }
              }, '#paypal-button');
            
            </script>


                <br>
                <a href="{% url 'gallery:shopByStyle' %}" class="btn btn-info my-2 my-sm-0">Continue Shopping</a>
            </div>
        </div>
    </div>
    <br>
{% endif %}
{% endblock %}